### PR TITLE
Support custom name and ID attributes

### PR DESCRIPTION
**Pull request by CUnknown**
Hi! Thanks for this package, it really helped me getting trix with attachments working in my react application.

I had two problems with the implmentation, which I thought I could share:

- My project already imported Trix as a module. Because some weird combination, webpack thinks that the included Trix is different from the Trix that is included in the react-trix-rte. It resulted in a empty object when I imported Trix in my custom code. Removing the import from the react-trix-rte component implementation, fixed this issue. The import itself was done in this component only as a nice service, because it is not really used in the code of the component itself.
- In parts of our application not yet migrated to react, I want to create a Trix editor component in a simple form input definition for the plain old forms. For this to work, the input has to have a name, and sometimes an ID that fits the form context. Therefore I needed to be able to set the ID and the name as a property of the react component. Now I can pass the ID and the name to the component when calling the react component with the rails-react `reac_component` helper. 

Hope this helps!

### CODE REVIEW

**Comment by abhaynikam** [comment]
@CUnknown PR looks good to me ❤️ . Could you add a changelog entry for both the problem PR resolves and add your GitHub id? I will test and merge it by today EOD and release a new version of the package. 

Thank you for your work 🎉

**Comment by CUnknown** [comment]
@abhaynikam Something like this?

**Review by abhaynikam — APPROVED** [review]
@CUnknown LGTM 🎉 . Will test it once and merge it. Thanks ❤️

**Comment by abhaynikam** [comment]
Released V1.0.7. Please feel free to upgrade. This is a breaking change for people upgrading unless manually `import Trix from 'trix';` is added.

**Pull request merged**
