### PR TITLE
Update Storybook

### PR DESCRIPTION
**Pull request by alejo4373**
I apologize for the delay. This pull requests updates storybook to the latest version. I verified manually that all stories still worked correctly.

### CODE REVIEW

**Comment by abhaynikam** [comment]
@alejo4373 Do we need to push storybook-static? IMO we could exclude it. Maybe we can try removing it once and I'll try compile and deploy. WDYT? 

Thanks for the PR ❤️

**Comment by abhaynikam** [comment]
@alejo4373 can you resolve the merge conflict? let's ship this PR as well. 😊

**Comment by alejo4373** [comment]
@abhaynikam I think we are good to go. Thanks for pinging me 👍.

**Comment by abhaynikam** [comment]
Thanks @alejo4373 ❤️

**Pull request merged**
